<?php
/*************************************************************************************
 * pawn.php
 * --------
 * Author: Rafael Keramidas (Rafael@Keramid.as)
 *
 * Copyright: (c) 2004 Nigel McNie (http://qbnz.com/highlighter/)
 * Release Version: 1.0.8.11
 * Date Started: 2004/07/10
 *
 * Pawn (SA-MP) language file for GeSHi.
 *
 * CHANGES
 * -------
 * 2012/09/12 (1.0)
 *   -  First Release
 *
 *
 *************************************************************************************
 *
 *     SA-MP Pawn for GeSHi by Rafael Keramidas is released under GPLv3.
 *
 ************************************************************************************/

$language_data = array (
    'LANG_NAME' => 'Pawn',
    'COMMENT_SINGLE' => array(1 => '//', 2=> '#'),
    'COMMENT_MULTI' => array('/*' => '*/'),
    'COMMENT_REGEXP' => array(),
    'CASE_KEYWORDS' => GESHI_CAPS_NO_CHANGE,
    'QUOTEMARKS' => array("'", '"'),
    'ESCAPE_CHAR' => '\\',
    'KEYWORDS' => array(
		1 => array(
            'break', 'case', 'continue', 'default', 'do', 'else', 'for', 'foreach', 'goto', 'if', 
			'return', 'switch', 'throw', 'try', 'catch', 'while', 'public', 'private', 'protected',
			'static', 'Float', 'stock'
            ),
        2 => array(
            'false', 'true', 'null'
            ),
        3 => array(
            'AddMenuItem',
			'AddPlayerClass',
			'AddPlayerClassEx',
			'AddStaticPickup',
			'AddStaticVehicle',
			'AddStaticVehicleEx',
			'AddVehicleComponent',
			'AllowAdminTeleport',
			'AllowInteriorWeapons',
			'AllowPlayerTeleport',
			'ApplyAnimation',
			'Attach3DTextLabelToPlayer',
			'Attach3DTextLabelToVehicle',
			'AttachCameraToObject',
			'AttachCameraToPlayerObject',
			'AttachObjectToObject',
			'AttachObjectToPlayer',
			'AttachObjectToVehicle',
			'AttachPlayerObjectToPlayer',
			'AttachPlayerObjectToVehicle',
			'AttachTrailerToVehicle',
			'Ban',
			'BanEx',
			'CallLocalFunction',
			'CallRemoteFunction',
			'CancelEdit',
			'CancelSelectTextDraw',
			'ChangeVehicleColor',
			'ChangeVehiclePaintjob',
			'clamp',
			'ClearAnimations',
			'ConnectNPC',
			'Create3DTextLabel',
			'CreateExplosion',
			'CreateMenu',
			'CreateObject',
			'CreatePickup',
			'CreatePlayer3DTextLabel',
			'CreatePlayerObject',
			'CreatePlayerTextDraw',
			'CreateVehicle',
			'db_close',
			'db_field_name',
			'db_free_result',
			'db_get_field',
			'db_get_field_assoc',
			'db_next_row',
			'db_num_fields',
			'db_num_rows',
			'db_open',
			'db_query',
			'Delete3DTextLabel',
			'DeletePVar',
			'DeletePlayer3DTextLabel',
			'deleteproperty',
			'DestroyMenu',
			'DestroyObject',
			'DestroyPickup',
			'DestroyPlayerObject',
			'DestroyVehicle',
			'DetachTrailerFromVehicle',
			'DisableInteriorEnterExits',
			'DisableMenu',
			'DisableMenuRow',
			'DisableNameTagLOS',
			'DisablePlayerCheckpoint',
			'DisablePlayerRaceCheckpoint',
			'EditAttachedObject',
			'EditObject',
			'EditPlayerObject',
			'EnableStuntBonusForAll',
			'EnableStuntBonusForPlayer',
			'EnableZoneNames',
			'existproperty',
			'fblockread',
			'fblockwrite',
			'fclose',
			'fexist',
			'fgetchar',
			'flength',
			'float',
			'floatabs',
			'floatadd',
			'floatattan',
			'floatcmp',
			'floatcos',
			'floatdiv',
			'floatfract',
			'floatlog',
			'floatmul',
			'floatpower',
			'floatround',
			'floatsin',
			'floatsqroot',
			'floatstr',
			'floatsub',
			'floattan',
			'fmatch',
			'fopen',
			'ForceClassSelection',
			'format',
			'fputchar',
			'fread',
			'fremove',
			'fseek',
			'ftemp',
			'funcidx',
			'fwrite',
			'GameModeExit',
			'GameTextForAll',
			'GameTextForPlayer',
			'GangZoneCreate',
			'GangZoneDestroy',
			'GangZoneFlashForAll',
			'GangZoneFlashForPlayer',
			'GangZoneHideForAll',
			'GangZoneHideForPlayer',
			'GangZoneShowForAll',
			'GangZoneShowForPlayer',
			'GangZoneStopFlashForAll',
			'GangZoneStopFlashForPlayer',
			'GetAnimationName',
			'GetMaxPlayers',
			'GetNetworkStats',
			'GetObjectPos',
			'GetObjectRot',
			'GetPVarFloat',
			'GetPVarInt',
			'GetPVarNameAtIndex',
			'GetPVarString',
			'GetPVarType',
			'GetPVarsUpperIndex',
			'GetPlayerAmmo',
			'GetPlayerAnimationIndex',
			'GetPlayerArmour',
			'GetPlayerCameraFrontVector',
			'GetPlayerCameraMode',
			'GetPlayerCameraPos',
			'GetPlayerCameraUpVector',
			'GetPlayerColor',
			'GetPlayerDistanceFromPoint',
			'GetPlayerDrunkLevel',
			'GetPlayerFacingAngle',
			'GetPlayerFightingStyle',
			'GetPlayerHealth',
			'GetPlayerInterior',
			'GetPlayerIp',
			'GetPlayerKeys',
			'GetPlayerMenu',
			'GetPlayerMoney',
			'GetPlayerName',
			'GetPlayerNetworkStats',
			'GetPlayerObjectPos',
			'GetPlayerObjectRot',
			'GetPlayerPing',
			'GetPlayerPos',
			'GetPlayerScore',
			'GetPlayerSkin',
			'GetPlayerSpecialAction',
			'GetPlayerState',
			'GetPlayerSurfingObjectID',
			'GetPlayerSurfingVehicleID',
			'GetPlayerTargetPlayer',
			'GetPlayerTeam',
			'GetPlayerTime',
			'GetPlayerVehicleID',
			'GetPlayerVehicleSeat',
			'GetPlayerVelocity',
			'GetPlayerVersion',
			'GetPlayerVirtualWorld',
			'GetPlayerWantedLevel',
			'GetPlayerWeapon',
			'GetPlayerWeaponData',
			'GetPlayerWeaponState',
			'GetServerVarAsBool',
			'GetServerVarAsInt',
			'GetServerVarAsString',
			'GetTickCount',
			'GetVehicleComponentInSlot',
			'GetVehicleComponentType',
			'GetVehicleDamageStatus',
			'GetVehicleDistanceFromPoint',
			'GetVehicleHealth',
			'GetVehicleModel',
			'GetVehicleModelInfo',
			'GetVehiclePos',
			'GetVehicleRotationQuat',
			'GetVehicleTrailer',
			'GetVehicleVelocity',
			'GetVehicleVirtualWorld',
			'GetVehicleZAngle',
			'GetWeaponName',
			'getarg',
			'getdate',
			'getproperty',
			'gettime',
			'GivePlayerMoney',
			'GivePlayerWeapon',
			'HTTP',
			'heapspace',
			'HideMenuForPlayer',
			'InterpolateCameraLookAt',
			'InterpolateCameraPos',
			'IsObjectMoving',
			'IsPlayerAdmin',
			'IsPlayerAttachedObjectSlotUsed',
			'IsPlayerConnected',
			'IsPlayerHoldingObject',
			'IsPlayerInAnyVehicle',
			'IsPlayerInCheckpoint',
			'IsPlayerInRaceCheckpoint',
			'IsPlayerInRangeOfPoint',
			'IsPlayerInVehicle',
			'IsPlayerNPC',
			'IsPlayerObjectMoving',
			'IsPlayerStreamedIn',
			'IsTrailerAttachedToVehicle',
			'IsValidObject',
			'IsValidPlayerObject',
			'IsValidVehicle',
			'IsVehicleStreamedIn',
			'ispacked',
			'Kick',
			'KillTimer',
			'LimitGlobalChatRadius',
			'LimitPlayerMarkerRadius',
			'LinkVehicleToInterior',
			'ManualVehicleEngineAndLights',
			'memcpy',
			'MoveObject',
			'MovePlayerObject',
			'PlayAudioStreamForPlayer',
			'PlayCrimeReportForPlayer',
			'PlayerPlaySound',
			'PlayerSpectatePlayer',
			'PlayerSpectateVehicle',
			'PlayerTextDrawAlignment',
			'PlayerTextDrawBackgroundColor',
			'PlayerTextDrawBoxColor',
			'PlayerTextDrawColor',
			'PlayerTextDrawDestroy',
			'PlayerTextDrawFont',
			'PlayerTextDrawHide',
			'PlayerTextDrawLetterSize',
			'PlayerTextDrawSetOutline',
			'PlayerTextDrawSetProportional',
			'PlayerTextDrawSetSelectable',
			'PlayerTextDrawSetShadow',
			'PlayerTextDrawSetString',
			'PlayerTextDrawShow',
			'PlayerTextDrawTextSize',
			'PlayerTextDrawUseBox',
			'print',
			'printf',
			'PutPlayerInVehicle',
			'random',
			'RemoveBuildingForPlayer',
			'RemovePlayerAttachedObject',
			'RemovePlayerFromVehicle',
			'RemovePlayerMapIcon',
			'RemoveVehicleComponent',
			'RepairVehicle',
			'ResetPlayerMoney',
			'ResetPlayerWeapons',
			'SelectObject',
			'SelectTextDraw',
			'SendClientMessage',
			'SendClientMessageToAll',
			'SendDeathMessage',
			'SendPlayerMessageToAll',
			'SendPlayerMessageToPlayer',
			'SendRconCommand',
			'SetCameraBehindPlayer',
			'SetDeathDropAmount',
			'SetDisabledWeapons',
			'SetGameModeText',
			'SetGravity',
			'SetMenuColumnHeader',
			'SetNameTagDrawDistance',
			'SetObjectMaterial',
			'SetObjectMaterialText',
			'SetObjectPos',
			'SetObjectRot',
			'SetPVarFloat',
			'SetPVarInt',
			'SetPVarString',
			'SetPlayerAmmo',
			'SetPlayerArmedWeapon',
			'SetPlayerArmour',
			'SetPlayerAttachedObject',
			'SetPlayerCameraLookAt',
			'SetPlayerCameraPos',
			'SetPlayerChatBubble',
			'SetPlayerCheckpoint',
			'SetPlayerColor',
			'SetPlayerDrunkLevel',
			'SetPlayerFacingAngle',
			'SetPlayerFightingStyle',
			'SetPlayerHealth',
			'SetPlayerHoldingObject',
			'SetPlayerInterior',
			'SetPlayerMapIcon',
			'SetPlayerMarkerForPlayer',
			'SetPlayerName',
			'SetPlayerObjectMaterial',
			'SetPlayerObjectMaterialText',
			'SetPlayerObjectPos',
			'SetPlayerObjectRot',
			'SetPlayerPos',
			'SetPlayerPosFindZ',
			'SetPlayerRaceCheckpoint',
			'SetPlayerScore',
			'SetPlayerShopName',
			'SetPlayerSkillLevel',
			'SetPlayerSkin',
			'SetPlayerSpecialAction',
			'SetPlayerTeam',
			'SetPlayerTime',
			'SetPlayerVelocity',
			'SetPlayerVirtualWorld',
			'SetPlayerWantedLevel',
			'SetPlayerWeather',
			'SetPlayerWorldBounds',
			'SetSpawnInfo',
			'SetTeamCount',
			'SetTimer',
			'SetTimerEx',
			'SetVehicleAngularVelocity',
			'SetVehicleHealth',
			'SetVehicleNumberPlate',
			'SetVehicleParamsEx',
			'SetVehicleParamsForPlayer',
			'SetVehiclePos',
			'SetVehicleToRespawn',
			'SetVehicleVelocity',
			'SetVehicleVirtualWorld',
			'SetVehicleZAngle',
			'SetWeather',
			'SetWorldTime',
			'setproperty',
			'ShowMenuForPlayer',
			'ShowNameTags',
			'ShowPlayerDialog',
			'ShowPlayerMarkers',
			'ShowPlayerNameTagForPlayer',
			'SpawnPlayer',
			'StartRecordingPlayerData',
			'StopAudioStreamForPlayer',
			'StopObject',
			'StopPlayerHoldingObject',
			'StopPlayerObject',
			'StopRecordingPlayerData',
			'strcat',
			'strcmp',
			'strdel',
			'strfind',
			'strins',
			'strlen',
			'strmid',
			'strpack',
			'strunpack',
			'strval',
			'TextDrawAlignment',
			'TextDrawBackgroundColor',
			'TextDrawBoxColor',
			'TextDrawColor',
			'TextDrawCreate',
			'TextDrawDestroy',
			'TextDrawFont',
			'TextDrawHideForAll',
			'TextDrawHideForPlayer',
			'TextDrawLetterSize',
			'TextDrawSetOutline',
			'TextDrawSetProportional',
			'TextDrawSetSelectable',
			'TextDrawSetShadow',
			'TextDrawSetString',
			'TextDrawShowForAll',
			'TextDrawShowForPlayer',
			'TextDrawTextSize',
			'TextDrawUseBox'
            ),
        4 => array(
            'enum', 'new', 'const'
            ), 
        5 => array(
            'OnDialogResponse',
			'OnEnterExitModShop',
			'OnFilterScriptExit',
			'OnFilterScriptInit',
			'OnGameModeExit',
			'OnGameModeInit',
			'OnObjectMoved',
			'OnPlayerClickMap',
			'OnPlayerClickPlayer',
			'OnPlayerClickPlayerTextDraw',
			'OnPlayerClickTextDraw',
			'OnPlayerCommandText',
			'OnPlayerConnect',
			'OnPlayerDeath',
			'OnPlayerDisconnect',
			'OnPlayerEditAttachedObject',
			'OnPlayerEditObject',
			'OnPlayerEnterCheckpoint',
			'OnPlayerEnterRaceCheckpoint',
			'OnPlayerEnterVehicle',
			'OnPlayerExitVehicle',
			'OnPlayerExitedMenu',
			'OnPlayerGiveDamage',
			'OnPlayerInteriorChange',
			'OnPlayerKeyStateChange',
			'OnPlayerLeaveCheckpoint',
			'OnPlayerLeaveRaceCheckpoint',
			'OnPlayerObjectMoved',
			'OnPlayerPickUpPickup',
			'OnPlayerPrivmsg',
			'OnPlayerRequestClass',
			'OnPlayerRequestSpawn',
			'OnPlayerSelectObject',
			'OnPlayerSelectedMenuRow',
			'OnPlayerSpawn',
			'OnPlayerStateChange',
			'OnPlayerStreamIn',
			'OnPlayerStreamOut',
			'OnPlayerTakeDamage',
			'OnPlayerTeamPrivmsg',
			'OnPlayerText',
			'OnPlayerUpdate',
			'OnRconCommand',
			'OnRconLoginAttempt',
			'OnUnoccupiedVehicleUpdate',
			'OnVehicleDamageStatusUpdate',
			'OnVehicleDeath',
			'OnVehicleMod',
			'OnVehiclePaintjob',
			'OnVehicleRespray',
			'OnVehicleSpawn',
			'OnVehicleStreamIn',
			'OnVehicleStreamOut'
            )
		),
	'SYMBOLS' => array(
        '(', ')', '[', ']', '{', '}',
        '+', '-', '*', '/', '%',
        '!', '&', '|', '^',
        '<', '>', '=',
        '?', ':', ';',
        ),
    'CASE_SENSITIVE' => array(
        GESHI_COMMENTS => false,
        1 => false,
        2 => false,
        3 => false,
        4 => false,
        5 => false,
        ),
    'STYLES' => array(
        'KEYWORDS' => array(
            1 => 'color: #b1b100;',
            2 => 'color: #000000; font-weight: bold;',
            3 => 'color: #000066;',
            4 => 'color: #993333;',
            5 => 'color: #63648C;'
            ),
        'COMMENTS' => array(
            1 => 'color: #808080; font-style: italic;',
            2 => 'color: #339933;',
            'MULTI' => 'color: #808080; font-style: italic;'
            ),
        'ESCAPE_CHAR' => array(
            0 => 'color: #000099; font-weight: bold;'
            ),
        'BRACKETS' => array(
            0 => 'color: #66cc66;'
            ),
        'STRINGS' => array(
            0 => 'color: #ff0000;'
            ),
        'NUMBERS' => array(
            0 => 'color: #cc66cc;'
            ),
        'METHODS' => array(
            1 => 'color: #202020;',
            2 => 'color: #202020;'
            ),
        'SYMBOLS' => array(
            0 => 'color: #66cc66;'
            ),
        'REGEXPS' => array(
            ),
        'SCRIPT' => array(
            )
        ),
    'URLS' => array(
        1 => '',
        2 => '',
        3 => 'http://wiki.sa-mp.com/wiki/{FNAME}',
        4 => '',
        5 => 'http://wiki.sa-mp.com/wiki/{FNAME}'
        ),
    'OOLANG' => false,
    'OBJECT_SPLITTERS' => array(
        ),
    'REGEXPS' => array(
        ),
    'STRICT_MODE_APPLIES' => GESHI_NEVER,
    'SCRIPT_DELIMITERS' => array(
        ),
    'HIGHLIGHT_STRICT_BLOCK' => array(
        )
);